version: '3.3'
services:
  app:
    build:
      context:  .
      dockerfile: Dockerfile
    expose:
      - "8080"
    links:
      - redis
 
  proxy:
    build:
      context:  ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
    links:
      - app

  redis:
    image: redis
    ports:
      - "6379:6379"